modLoader="javafml"
loaderVersion="[40,)"
license="Creative Commons Attribution-ShareAlike 4.0"

[[mods]]
modId="mcrssmod"
version="0.1.0"
displayName="Realistic Survival System"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="KOR_APUcard, MCreator"
description='''
Makes Minecraft's survival systems to more realistic.
'''

[[dependencies.mcrssmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.mcrssmod]]
    modId="mekanism"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

