modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-ShareAlike 4.0"

[[mods]]
modId="mcrssmod"
version="1.0.0"
displayName="Realistic Survival System"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="KOR_APUcard, MCreator"

[[dependencies.mcrssmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.mcrssmod]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcrssmod]]
    modId="mekanism"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
